{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "frontend.fullname" . }}-allow-kong
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          {{- with .Values.networkPolicy.kongNamespaceLabels }}
          {{- toYaml . | nindent 10 }}
          {{- else }}
          name: kong
          {{- end }}
    ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
{{- end }}









